/* tslint:disable */
/* eslint-disable */
/**
 * Wholesome Living Backend
 * A backend for Wholesome Living written in Golang backend API using Fiber and MongoDB
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface MeditationCreateMeditationRequest
 */
export interface MeditationCreateMeditationRequest {
    /**
     * 
     * @type {number}
     * @memberof MeditationCreateMeditationRequest
     */
    'endTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof MeditationCreateMeditationRequest
     */
    'meditationTime'?: number;
}
/**
 * 
 * @export
 * @interface MeditationCreateMeditationResponse
 */
export interface MeditationCreateMeditationResponse {
    /**
     * 
     * @type {string}
     * @memberof MeditationCreateMeditationResponse
     */
    'id'?: string;
}
/**
 * 
 * @export
 * @interface MeditationGet200ResponseInner
 */
export interface MeditationGet200ResponseInner {
    /**
     * 
     * @type {number}
     * @memberof MeditationGet200ResponseInner
     */
    'endTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeditationGet200ResponseInner
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof MeditationGet200ResponseInner
     */
    'meditationTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeditationGet200ResponseInner
     */
    'userId'?: string;
}
/**
 * 
 * @export
 * @interface MeditationGetMeditationResponse
 */
export interface MeditationGetMeditationResponse {
    /**
     * 
     * @type {number}
     * @memberof MeditationGetMeditationResponse
     */
    'endTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeditationGetMeditationResponse
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof MeditationGetMeditationResponse
     */
    'meditationTime'?: number;
    /**
     * 
     * @type {string}
     * @memberof MeditationGetMeditationResponse
     */
    'userId'?: string;
}
/**
 * 
 * @export
 * @interface UserCreateUserRequest
 */
export interface UserCreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserRequest
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserRequest
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserRequest
     */
    'lastName'?: string;
}
/**
 * 
 * @export
 * @interface UserCreateUserResponse
 */
export interface UserCreateUserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserCreateUserResponse
     */
    'id'?: string;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const UserPluginType = {
    PluginTypeMeditation: 'meditation',
    PluginTypeWorkout: 'workout'
} as const;

export type UserPluginType = typeof UserPluginType[keyof typeof UserPluginType];


/**
 * 
 * @export
 * @interface UserUpdateUserRequest
 */
export interface UserUpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserRequest
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateUserRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {Array<UserPluginType>}
     * @memberof UserUpdateUserRequest
     */
    'plugins'?: Array<UserPluginType>;
}
/**
 * 
 * @export
 * @interface UserUserDB
 */
export interface UserUserDB {
    /**
     * 
     * @type {number}
     * @memberof UserUserDB
     */
    'createdAt'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUserDB
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDB
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDB
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDB
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUserDB
     */
    'lastName'?: string;
    /**
     * 
     * @type {Array<UserPluginType>}
     * @memberof UserUserDB
     */
    'plugins'?: Array<UserPluginType>;
}

/**
 * MeditationApi - axios parameter creator
 * @export
 */
export const MeditationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * fetch all meditation sessions of a user.
         * @summary Get all meditation session
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationGet: async (userId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/meditation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId != null) {
                localVarHeaderParameter['userId'] = String(userId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * fetch a single meditation session.
         * @summary Get a meditation session
         * @param {string} id Meditation ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationIdGet: async (id: string, userId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('meditationIdGet', 'id', id)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('meditationIdGet', 'userId', userId)
            const localVarPath = `/meditation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId != null) {
                localVarHeaderParameter['userId'] = String(userId);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new meditation.
         * @summary Create meditation.
         * @param {MeditationCreateMeditationRequest} meditation Meditation to create
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationPost: async (meditation: MeditationCreateMeditationRequest, userId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'meditation' is not null or undefined
            assertParamExists('meditationPost', 'meditation', meditation)
            const localVarPath = `/meditation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId != null) {
                localVarHeaderParameter['userId'] = String(userId);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(meditation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeditationApi - functional programming interface
 * @export
 */
export const MeditationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeditationApiAxiosParamCreator(configuration)
    return {
        /**
         * fetch all meditation sessions of a user.
         * @summary Get all meditation session
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meditationGet(userId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MeditationGet200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meditationGet(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * fetch a single meditation session.
         * @summary Get a meditation session
         * @param {string} id Meditation ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meditationIdGet(id: string, userId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeditationGetMeditationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meditationIdGet(id, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Creates a new meditation.
         * @summary Create meditation.
         * @param {MeditationCreateMeditationRequest} meditation Meditation to create
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meditationPost(meditation: MeditationCreateMeditationRequest, userId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeditationCreateMeditationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meditationPost(meditation, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MeditationApi - factory interface
 * @export
 */
export const MeditationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeditationApiFp(configuration)
    return {
        /**
         * fetch all meditation sessions of a user.
         * @summary Get all meditation session
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationGet(userId?: string, options?: any): AxiosPromise<Array<MeditationGet200ResponseInner>> {
            return localVarFp.meditationGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * fetch a single meditation session.
         * @summary Get a meditation session
         * @param {string} id Meditation ID
         * @param {string} userId User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationIdGet(id: string, userId: string, options?: any): AxiosPromise<MeditationGetMeditationResponse> {
            return localVarFp.meditationIdGet(id, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new meditation.
         * @summary Create meditation.
         * @param {MeditationCreateMeditationRequest} meditation Meditation to create
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meditationPost(meditation: MeditationCreateMeditationRequest, userId?: string, options?: any): AxiosPromise<MeditationCreateMeditationResponse> {
            return localVarFp.meditationPost(meditation, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeditationApi - object-oriented interface
 * @export
 * @class MeditationApi
 * @extends {BaseAPI}
 */
export class MeditationApi extends BaseAPI {
    /**
     * fetch all meditation sessions of a user.
     * @summary Get all meditation session
     * @param {string} [userId] User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeditationApi
     */
    public meditationGet(userId?: string, options?: AxiosRequestConfig) {
        return MeditationApiFp(this.configuration).meditationGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * fetch a single meditation session.
     * @summary Get a meditation session
     * @param {string} id Meditation ID
     * @param {string} userId User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeditationApi
     */
    public meditationIdGet(id: string, userId: string, options?: AxiosRequestConfig) {
        return MeditationApiFp(this.configuration).meditationIdGet(id, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new meditation.
     * @summary Create meditation.
     * @param {MeditationCreateMeditationRequest} meditation Meditation to create
     * @param {string} [userId] User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeditationApi
     */
    public meditationPost(meditation: MeditationCreateMeditationRequest, userId?: string, options?: AxiosRequestConfig) {
        return MeditationApiFp(this.configuration).meditationPost(meditation, userId, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * fetch every user available.
         * @summary Get all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * fetch a user by id.
         * @summary Get a user.
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdGet', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * creates one user.
         * @summary Create one user.
         * @param {UserCreateUserRequest} user User to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPost: async (user: UserCreateUserRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'user' is not null or undefined
            assertParamExists('usersPost', 'user', user)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(user, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * update a user by id.
         * @summary Update a user.
         * @param {UserUpdateUserRequest} user User to update
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPut: async (user: UserUpdateUserRequest, userId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'user' is not null or undefined
            assertParamExists('usersPut', 'user', user)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId != null) {
                localVarHeaderParameter['userId'] = String(userId);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(user, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * fetch every user available.
         * @summary Get all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserUserDB>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * fetch a user by id.
         * @summary Get a user.
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUserDB>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * creates one user.
         * @summary Create one user.
         * @param {UserCreateUserRequest} user User to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersPost(user: UserCreateUserRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserCreateUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersPost(user, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * update a user by id.
         * @summary Update a user.
         * @param {UserUpdateUserRequest} user User to update
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersPut(user: UserUpdateUserRequest, userId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserUserDB>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersPut(user, userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * fetch every user available.
         * @summary Get all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(options?: any): AxiosPromise<Array<UserUserDB>> {
            return localVarFp.usersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * fetch a user by id.
         * @summary Get a user.
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet(id: string, options?: any): AxiosPromise<UserUserDB> {
            return localVarFp.usersIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * creates one user.
         * @summary Create one user.
         * @param {UserCreateUserRequest} user User to create
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPost(user: UserCreateUserRequest, options?: any): AxiosPromise<UserCreateUserResponse> {
            return localVarFp.usersPost(user, options).then((request) => request(axios, basePath));
        },
        /**
         * update a user by id.
         * @summary Update a user.
         * @param {UserUpdateUserRequest} user User to update
         * @param {string} [userId] User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersPut(user: UserUpdateUserRequest, userId?: string, options?: any): AxiosPromise<UserUserDB> {
            return localVarFp.usersPut(user, userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * fetch every user available.
     * @summary Get all users.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersGet(options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * fetch a user by id.
     * @summary Get a user.
     * @param {string} id User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersIdGet(id: string, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * creates one user.
     * @summary Create one user.
     * @param {UserCreateUserRequest} user User to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersPost(user: UserCreateUserRequest, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersPost(user, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * update a user by id.
     * @summary Update a user.
     * @param {UserUpdateUserRequest} user User to update
     * @param {string} [userId] User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersPut(user: UserUpdateUserRequest, userId?: string, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersPut(user, userId, options).then((request) => request(this.axios, this.basePath));
    }
}


